### PR TITLE
Fix minor typo in termination criteria description

### PR DESCRIPTION
**Pull request by ohinder**
No need to run unit test as change is minor.

### CODE REVIEW

**Comment by mlubin** [comment]
> No need to run unit test as change is minor.

Unit tests are automatically run on every PR.

**Review by mlubin — APPROVED** [review]
Please re-trigger the CLA bot if you've registered.

**Comment by ohinder** [comment]
How do I retrigger the PLA bot?

**Comment by mlubin** [comment]
> Once you've signed (or fixed any issues), please reply here with `@googlebot I signed it!` and we'll verify it.

**Pull request merged**
